#!/bin/bash

# создаем "с нуля" ветку в git
server="git@server_ip"
repoDir="Algo500.data"
currDir=$(pwd)		# текущая директория
rootDir=$1		# корневая директория, локальная для git репозитория 
uid=$2			# идентификатор пользователя
teid=$3			# идентификатор типа эксперимента
if [ "$#" -lt 3 ]; then
    echo "Недостаточно аргументов"
    exit 1
fi
#
cd $rootDir
if [ -d $uid ]; then
    cd $uid
    git init
    git remote add origin $server:$repoDir
    git checkout -b "$teid"
    git add .
    git commit -a -m "Create $teid branch" 
    git push -u origin "$teid"
fi
#
cd $currDir

