#!/bin/bash

# Создаем "с нуля" папку для эксперимента
server="git@server_ip"
repoDir="Algo500.data"
currDir=$(pwd)		# текущая директория
rootDir=$1		# корневая директория, локальная для git репозитория 
uid=$2			# идентификатор пользователя
teid=$3			# идентификатор типа эксперимента
eid=$4			# идентификатор эксперимента
lid=$5			# идентификатор запуска
if [ "$#" -lt 5 ]; then
    echo "Недостаточно аргументов"
    echo $server:$repoDir
    exit 1
fi
#
cd $rootDir
if [ ! -d $uid ]; then
    mkdir $uid
else
    cd $uid; rm -fr *; cd ..
fi
#
cd $uid
x=$(git clone --branch="${teid}_${eid}" ${server}:${repoDir})
echo $x
cd $rootDir/$uid/$repoDir/$teid/$eid
#
if [ ! -z $5 ]; then
    if ! [ -d $lid ]; then
	mkdir $lid
	cd $lid
	cp $currDir/templates/README_LAUNCH.MD README.MD
    fi
fi
cd $currDir

