#!/bin/bash

currDir=$(pwd)
rootDir=$1
uid=$2
teid=$3
if [ "$#" -lt 3 ]; then
    echo "Недостаточно аргументов"
    exit 1
fi
#
cd $rootDir
if ! [ -d $uid ]; then
    mkdir $uid
fi
#
cd $uid
if ! [ -z $3 ]; then
    if ! [ -d $teid ]; then
	mkdir $teid
	cd $teid
	mkdir common
	cp $currDir/templates/README_COMMON.MD common/README.MD
	cp $currDir/templates/README_TE.MD README.MD
    fi
fi
cd $currDir

